# Raw dotfile symlinks (the "thin wrapper" heart of the port).
#
# Every file/dir under ../../home is symlinked into place OUT OF THE NIX STORE
# via config.lib.file.mkOutOfStoreSymlink, pointing through ~/.dotfiles. That
# preserves chezmoi's "edit a config and it's live immediately" property — no
# rebuild needed for a raw config change. Nix only owns the *packages* these
# configs drive (installed in packages.nix); it does not reproduce their
# in-shell init.
#
# Gating comes entirely from the machine's `identity` (personal/work/lab) and
# `caps` set, threaded in via extraSpecialArgs — no hostname checks here.
#
# Whole directories are linked as a single symlink where every file in them is
# ungated and uniform (nvim, yazi, tmux, ...). Directories whose members gate
# differently (profile.d, mcp/machine, skills/machine) are linked file-by-file.
#
# Ownership boundaries (avoid duplicate home.file keys across modules):
#   - Tiling trees (aerospace/, sketchybar/, borders/) are owned by tiling.nix.
#   - mise config + claude settings.json are generated by dev-tools.nix/ai-stack.nix.
#   - Encrypted secrets (~/.config/zsh/.env, ~/.ssh/config, work claude skills)
#     are materialized by secrets.nix — NOT symlinked here.
{ config, lib, caps, identity, ... }:

let
  dotfiles = "${config.home.homeDirectory}/.dotfiles";

  # Repo path == home-relative target path (the home/ tree mirrors ~), so a
  # single relative path names both the link source and its home.file key.
  link = path: config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/${path}";

  # Turn a list of relative paths into { "<path>".source = link "<path>"; ... }.
  mkLinks = paths: lib.genAttrs paths (p: { source = link p; });

  # Machine-type overlay filename shared by mcp + skills (files are named
  # personal.json / work.json; identity is personal / work).
  overlay = "${identity}.json";
in
{
  home.file = lib.mkMerge [
    # ---- all machines -----------------------------------------------------
    (mkLinks [
      # z4h shell stack (z4h owns lifecycle; keep every file raw — see shell.nix).
      ".zshenv"
      ".config/zsh/.zshenv"
      ".config/zsh/.zshrc"
      ".config/zsh/.zprofile"
      ".config/zsh/.p10k.zsh"
      ".config/zsh/lib" # rebuild.zsh (replaces the retired chezmoi-apply lib)
      ".config/zsh/profile.d/worktrunk-aliases.zsh"
      ".config/zsh/profile.d/common-env.zsh" # non-secret flags (was the agenix zsh-env secret; WS1)

      # Editor / TUI / terminal configs.
      ".config/nvim" # stock LazyVim tree; LazyVim rewrites lazy-lock.json in place
      ".config/yazi"
      ".config/tmux"
      ".config/ghostty" # harmless everywhere; link always regardless of gui cap
      ".ideavimrc"

      # Dev tooling configs (mise config itself is generated in dev-tools.nix).
      ".config/git" # config (renamed from config.tmpl by dev-tools) + .gitignore_global
      ".config/jj"
      ".config/worktrunk"
      ".config/dev-container"
      ".config/nushell/config.nu" # link the file, not the dir (nushell writes history/env.nu there)
      ".duckdbrc"

      # Copilot IntelliJ instructions (single file; copilot writes runtime state in the dir).
      ".config/github-copilot/intellij/global-copilot-instructions.md"

      # Claude Code statusline + hooks. NOTE: settings.json is NOT linked here —
      # it is jq-merged by an activation script in ai-stack.nix so Claude's own
      # in-tool edits survive. CLAUDE.md is deployed per the locked gating map
      # (see report note: phase1 flagged the old chezmoi setup ignored it).
      ".claude/statusline-command.sh"
      ".claude/CLAUDE.md"
      ".claude/hooks/agent-journal-stop.sh"
      ".claude/hooks/emit-routing-context.sh"
      ".claude/hooks/wt-create.sh"
      ".claude/hooks/wt-remove.sh"
    ])

    # ---- identity: personal ----------------------------------------------
    (lib.optionalAttrs (identity == "personal") (mkLinks [
      ".config/zsh/profile.d/personal-shell-functions.zsh"
      ".config/zsh/profile.d/personal-secrets.zsh" # sources ~/.config/zsh/.personal.env (op-rendered)
      ".config/op/render-manifest" # op-render reads this at its default path (WS1)
      ".config/hippo" # local LM brain client config (config.toml + redact.toml)
    ]))

    # ---- identity: work ---------------------------------------------------
    (lib.optionalAttrs (identity == "work") (mkLinks [
      ".config/zsh/profile.d/work-shell-functions.zsh"
      ".config/zsh/profile.d/work-aws-shell-functions.zsh"
      ".config/zsh/profile.d/work-secrets.zsh"
    ]))

    # ---- NOT work (homelab access over Tailscale: personal only) ---------
    (lib.optionalAttrs (identity != "work") (mkLinks [
      ".config/zsh/profile.d/tailscale.zsh"
    ]))

    # ---- caps.atuin -------------------------------------------------------
    # Link only the config file; atuin writes history.db into the same dir.
    (lib.optionalAttrs caps.atuin (mkLinks [
      ".config/atuin/config.toml"
    ]))

    # ---- caps.mcp ---------------------------------------------------------
    # Master config + this machine's overlay. sync-mcp-configs (sync-hooks.nix)
    # reads these at activation time and also consults ~/.config/mcp/overrides/
    # if present — so guarantee that dir exists via a store-linked .keep marker
    # (sync globs overrides/*.json, so .keep is ignored).
    (lib.optionalAttrs caps.mcp (mkLinks [
      ".config/mcp/mcp-master.json"
      ".config/mcp/machine/${overlay}"
    ]))
    (lib.optionalAttrs caps.mcp {
      ".config/mcp/overrides/.keep".text = "";
    })

    # ---- caps.skills ------------------------------------------------------
    # Manifest + this machine's overlay; sync-skills (sync-hooks.nix) reads them.
    (lib.optionalAttrs caps.skills (mkLinks [
      ".config/skills/skills-master.json"
      ".config/skills/machine/${overlay}"
    ]))

    # ---- caps.agent_journal ----------------------------------------------
    (lib.optionalAttrs caps.agent_journal (mkLinks [
      ".config/agent-journal" # config.toml + workstreams.toml (rendered static by ai-stack)
      ".local/bin/agent-journal"
      ".local/bin/agent-note"
    ]))
  ];
}
