# Raw dotfile symlinks (the "thin wrapper" heart of the port).
#
# Every file/dir under ../../home is symlinked into place OUT OF THE NIX STORE
# via config.lib.file.mkOutOfStoreSymlink, pointing through ~/.dotfiles. That
# preserves chezmoi's "edit a config and it's live immediately" property — no
# rebuild needed for a raw config change. Nix only owns the *packages* these
# configs drive (installed in packages.nix); it does not reproduce their
# in-shell init.
#
# Gating comes entirely from the machine's `identity` (personal/work/lab) and
# `caps` set, threaded in via extraSpecialArgs — no hostname checks here.
#
# Whole directories are linked as a single symlink where every file in them is
# ungated and uniform (nvim, yazi, tmux, ...). Directories whose members gate
# differently (profile.d, mcp/machine, skills/machine) are linked file-by-file.
#
# Ownership boundaries (avoid duplicate home.file keys across modules):
#   - Tiling trees (aerospace/, sketchybar/, borders/) are owned by tiling.nix.
#   - mise config + claude settings.json are generated by dev-tools.nix/ai-stack.nix.
#   - Personal secret targets (~/.config/zsh/.personal.env,
#     ~/.ssh/config.d/10-homelab.conf) are rendered by op-render. This repo
#     materializes no work secrets; that is the external overlay's custody.
#
# SSH config tiering (see home/.ssh/config for the full contract):
#   1. universal      — ~/.ssh/config, plain symlink, EVERY machine
#   2. personal hosts — ~/.ssh/config.d/10-*.conf, op-rendered, personal only
#   3. work hosts     — ~/.ssh/config.d/20-*.conf, external overlay's to own
# Tier 1 is deliberately ungated: the 1Password agent, multiplexing, and the
# config.d seam are wanted identically everywhere, and it carries no op://
# reference so it needs no renderer.
{
  config,
  lib,
  caps,
  identity,
  ...
}:

let
  dotfiles = "${config.home.homeDirectory}/.dotfiles";

  # Repo path == home-relative target path (the home/ tree mirrors ~), so a
  # single relative path names both the link source and its home.file key.
  link = path: config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/${path}";
  repoLink = path: config.lib.file.mkOutOfStoreSymlink "${dotfiles}/${path}";
  forcedRepoLink = path: {
    source = repoLink path;
    force = true;
  };

  # Turn a list of relative paths into { "<path>".source = link "<path>"; ... }.
  mkLinks =
    paths:
    lib.genAttrs paths (p: {
      source = link p;
    });

  # Machine-type overlay filename shared by mcp + skills (files are named
  # personal.json / work.json; identity is personal / work).
  overlay = "${identity}.json";
in
{
  home.file = lib.mkMerge [
    # ---- all machines -----------------------------------------------------
    (mkLinks [
      # z4h shell stack (z4h owns lifecycle; keep every file raw — see shell.nix).
      ".zshenv"
      ".config/zsh/.zshenv"
      ".config/zsh/.zshrc"
      ".config/zsh/.zprofile"
      ".config/zsh/.p10k.zsh"
      ".config/zsh/lib" # rebuild.zsh (replaces the retired chezmoi-apply lib)
      ".config/zsh/profile.d/worktrunk-aliases.zsh"
      ".config/zsh/profile.d/common-env.zsh" # non-secret flags (was the zsh-env age secret; WS1)

      # Editor / TUI / terminal configs.
      ".config/nvim" # stock LazyVim tree; LazyVim rewrites lazy-lock.json in place
      ".config/yazi"
      ".config/tmux"
      ".config/ghostty" # harmless everywhere; link always regardless of gui cap
      ".ideavimrc"

      # Dev tooling configs (mise config itself is generated in dev-tools.nix).
      ".config/git" # config (renamed from config.tmpl by dev-tools) + .gitignore_global
      # Link only the config: jj writes mutable repository metadata beneath
      # ~/.config/jj/repos, which must not land in the dotfiles checkout.
      ".config/jj/config.toml"
      ".config/dev-container"
      ".config/nushell/config.nu" # link the file, not the dir (nushell writes history/env.nu there)

      # Copilot IntelliJ instructions (single file; copilot writes runtime state in the dir).
      ".config/github-copilot/intellij/global-copilot-instructions.md"

      # gh account router. Deliberately on PATH rather than only a zsh function:
      # ~/.local/bin precedes the mise shim dir, so this shadows `gh` for EVERY
      # caller including subprocesses — which is the whole point, since a shell
      # function is invisible to the non-interactive bash that coding agents and
      # `npx gh-axi` run through. Ungated: the dual-account problem it solves is
      # worst on the work machine, which is logged into both accounts.
      ".local/bin/gh"

      # Claude Code statusline + hooks. NOTE: settings.json is NOT linked here —
      # it is jq-merged by an activation script in ai-stack.nix so Claude's own
      # in-tool edits survive. CLAUDE.md is deployed per the locked gating map
      # (see report note: phase1 flagged the old chezmoi setup ignored it).
      ".claude/statusline-command.sh"
      ".claude/CLAUDE.md"
      ".claude/hooks/agent-journal-stop.sh"
      ".claude/hooks/emit-routing-context.sh"
      ".claude/hooks/wt-create.sh"
      ".claude/hooks/wt-remove.sh"

      # Codex CLI: shared agent instructions + worktree hooks. AGENTS.md is
      # machine-invariant (it renders the shared global-agent-instructions body
      # with no per-host conditionals). The two hook scripts are byte-identical
      # to the Claude ones above. hooks.json is NOT linked here — it is generated
      # personal-only below (its only live hook is the personal hippo session
      # hook; the old chezmoi PreToolUse/PostToolUse template guards are dead).
      ".codex/AGENTS.md"
      ".codex/hooks/wt-create.sh"
      ".codex/hooks/wt-remove.sh"
    ])

    # ---- identity: personal ----------------------------------------------
    (lib.optionalAttrs (identity == "personal") (mkLinks [
      ".config/zsh/profile.d/personal-shell-functions.zsh"
      ".config/zsh/profile.d/personal-secrets.zsh" # sources ~/.config/zsh/.personal.env (op-rendered)
      ".config/op/render-manifest" # op-render reads this at its default path (WS1)
      ".config/op/adopt-policy.json" # exact allowlist for names-only reverse adoption
      ".local/bin/op-adopt" # guarded live secret -> 1Password adoption; dry-run by default
      ".config/hippo" # local LM brain client config (config.toml + redact.toml)
    ]))

    # Codex hooks.json (personal only). The chezmoi source deployed this on every
    # machine, but its PreToolUse/PostToolUse hooks were chezmoi-template guards
    # (encrypted_* block + execute-template validation) that are inert under nix,
    # leaving only the personal hippo SessionStart hook as live content. Generated
    # rather than symlinked so the hippo path binds to this machine's homeDir.
    (lib.optionalAttrs (identity == "personal") {
      ".codex/hooks.json".text = builtins.toJSON {
        hooks.SessionStart = [
          {
            hooks = [
              {
                type = "command";
                command = "${config.home.homeDirectory}/.local/share/hippo-brain/shell/claude-session-hook.sh";
              }
            ];
          }
        ];
      };
    })

    # ---- NOT work (homelab access over Tailscale: personal only) ---------
    (lib.optionalAttrs (identity != "work") (mkLinks [
      ".config/zsh/profile.d/tailscale.zsh"
    ]))

    # ---- atuin ------------------------------------------------------------
    # Deployed on EVERY machine; caps.atuin selects only WHICH variant. The
    # capability means "sync history to the self-hosted server" — it does not
    # mean "have a config at all". history_filter and the tmux popup are not
    # sync concerns, so they ship in both variants.
    #
    # An absent config is never a neutral state: atuin then runs on its own
    # defaults, which include a PUBLIC sync_address and no history_filter at
    # all. `atuin init zsh` also reads [tmux].enabled at init time and emits
    # ATUIN_TMUX_POPUP=false when it is missing, so the search UI renders
    # inline rather than in a popup.
    #
    # mkDefault leaves the external work wrapper room to outrank this, per the
    # override seam below and the aerospace precedent in tiling.nix.
    # Link only the config file; atuin writes history.db into the same dir.
    {
      ".config/atuin/config.toml".source = lib.mkDefault (
        link ".config/atuin/config.${if caps.atuin then "sync" else "local"}.toml"
      );
    }

    # Whole-file override seam for tools without native include support.
    # An external module's ordinary source definition outranks this default.
    {
      ".config/worktrunk".source = lib.mkDefault (link ".config/worktrunk");
    }

    # ---- caps.mcp ---------------------------------------------------------
    # Master config + this machine's overlay. sync-mcp-configs (sync-hooks.nix)
    # reads these at activation time and also consults ~/.config/mcp/overrides/
    # if present — so guarantee that dir exists via a store-linked .keep marker
    # (sync globs overrides/*.json, so .keep is ignored).
    (lib.optionalAttrs caps.mcp (mkLinks [
      ".config/mcp/mcp-master.json"

      # AI CLI tool configs gated with the MCP fan-out (matches .chezmoiignore:
      # these are dropped on machines without the mcp cap). Each tool writes its
      # own runtime state into the surrounding dir but not into these managed
      # files, so a single-file out-of-store symlink is safe (copilot -> other
      # files in ~/.copilot; cursor -> other files in ~/.cursor). OpenCode's
      # live config is generated by mcp_sync; the old rules.toml is ignored by
      # current OpenCode and is intentionally not carried into the Nix layout.
      ".copilot/settings.json"
      ".cursor/cli-config.json"
    ]))
    (lib.optionalAttrs caps.mcp {
      ".config/mcp/overrides/.keep".text = "";
      # mkDefault: an external overlay repo may take ownership of this
      # machine's overlay (LOCKED contract — declared seam).
      ".config/mcp/machine/${overlay}".source = lib.mkDefault (link ".config/mcp/machine/${overlay}");
    })

    # ---- caps.skills ------------------------------------------------------
    # Manifest + this machine's overlay; sync-skills (sync-hooks.nix) reads them.
    (lib.optionalAttrs caps.skills (mkLinks [
      ".config/skills/skills-master.json"
    ]))
    (lib.optionalAttrs caps.skills {
      # mkDefault: an external overlay repo may take ownership (LOCKED contract — declared seam).
      ".config/skills/machine/${overlay}".source = lib.mkDefault (
        link ".config/skills/machine/${overlay}"
      );
    })
    # Personal skill links previously pointed into the retired chezmoi source
    # tree. Own each tool-native link explicitly so deleting that checkout does
    # not strand Codex, Cursor, Copilot, OpenCode, or Junie.
    (lib.optionalAttrs (caps.skills && identity == "personal") {
      # NOTE: use-railway is vendored as a STATIC local copy under
      # skills/personal/use-railway and linked out-of-store below. Do NOT wire
      # the upstream railwayapp/railway-skills repo in as a pinned git source in
      # skills-master.json (the auto-refresh design discussed) until the upstream
      # PR that restores the removed injection guards is addressed — a 2026-07
      # `railway skills update --force` shipped a shell-injection (dal.py) and a
      # SQL-injection (pg-extensions.py) regression, both reverted here. Keeping
      # the copy static means no CLI/upstream refresh can silently overwrite it.
      ".config/opencode/skills/use-railway" = forcedRepoLink "skills/personal/use-railway";
      ".codex/skills/playwright" = forcedRepoLink "skills/personal/playwright";
      ".codex/skills/use-railway" = forcedRepoLink "skills/personal/use-railway";
      ".cursor/skills/use-railway" = forcedRepoLink "skills/personal/use-railway";
      ".copilot/skills/use-railway" = forcedRepoLink "skills/personal/use-railway";
      ".junie/skills/clerk" = forcedRepoLink "skills/personal/clerk";
      ".junie/skills/clerk-testing" = forcedRepoLink "skills/personal/clerk-testing";
      ".junie/skills/clerk-webhooks" = forcedRepoLink "skills/personal/clerk-webhooks";
      ".junie/skills/design-an-interface" = forcedRepoLink "skills/personal/design-an-interface";
      ".junie/skills/domain-model" = forcedRepoLink "skills/personal/domain-model";
      ".junie/skills/gh-axi" = forcedRepoLink "skills/personal/gh-axi";
      ".junie/skills/github-triage" = forcedRepoLink "skills/personal/github-triage";
      ".junie/skills/request-refactor-plan" = forcedRepoLink "skills/personal/request-refactor-plan";
      ".junie/skills/ubiquitous-language" = forcedRepoLink "skills/personal/ubiquitous-language";
    })

    # ---- caps.agent_journal ----------------------------------------------
    (lib.optionalAttrs caps.agent_journal (mkLinks [
      ".config/agent-journal" # config.toml + workstreams.toml (plain out-of-store symlinks)
      ".local/bin/agent-journal"
      ".local/bin/agent-note"
    ]))

    # ---- ssh tier 1: universal base (all machines) -------------------------
    # mkDefault so an external overlay can take the whole file over if it ever
    # needs to; the expectation is that it drops a config.d fragment instead.
    {
      ".ssh/config".source = lib.mkDefault (link ".ssh/config");
    }

    # ---- extension seam dirs (all machines) --------------------------------
    {
      # Real, neutral overlay roots avoid nesting external home.file entries
      # beneath the out-of-store .config/git and .config/tmux parent symlinks.
      #
      # ~/.ssh/config.d is now a live seam, not just a placeholder: tier-2
      # personal fragments are op-rendered into it and tier-3 work fragments
      # come from the external overlay. ~/.ssh/config includes it above every
      # Host block, so fragments win on first match.
      ".ssh/config.d/.keep".text = "";
      ".config/external-overlays/git/.keep".text = "";
      ".config/external-overlays/tmux/.keep".text = "";

      # ~/.claude/settings.d is the fragment seam for the Claude settings
      # merge (ai-stack.nix's claudeSettingsMerge activation): external
      # overlay repos drop JSON fragments here that deep-merge over the
      # managed block. Materialize the dir with a real .keep so it exists
      # even with no fragments present yet.
      ".claude/settings.d/.keep".text = "";
    }
  ];

  # One link deliberately routed through the public rawDotfiles API so the
  # in-repo build exercises the same code path external wrappers use.
  rawDotfiles.trees = [
    {
      root = "${dotfiles}/home";
      paths = [ ".duckdbrc" ];
    }
  ];
}
