# Raw dotfile symlinks (the "thin wrapper" heart of the port).
#
# Every file/dir under ../../home is symlinked into place OUT OF THE NIX STORE
# via config.lib.file.mkOutOfStoreSymlink, pointing through ~/.dotfiles. That
# preserves chezmoi's "edit a config and it's live immediately" property — no
# rebuild needed for a raw config change. Nix only owns the *packages* these
# configs drive (installed in packages.nix); it does not reproduce their
# in-shell init.
#
# Gating comes entirely from the machine's `identity` (personal/work/lab) and
# `caps` set, threaded in via extraSpecialArgs — no hostname checks here.
#
# Whole directories are linked as a single symlink where every file in them is
# ungated and uniform (nvim, yazi, tmux, ...). Directories whose members gate
# differently (profile.d, mcp/machine, skills/machine) are linked file-by-file.
#
# Ownership boundaries (avoid duplicate home.file keys across modules):
#   - Tiling trees (aerospace/, sketchybar/, borders/) are owned by tiling.nix.
#   - mise config + claude settings.json are generated by dev-tools.nix/ai-stack.nix.
#   - Encrypted secrets (~/.config/zsh/.env, ~/.ssh/config, work claude skills)
#     are materialized by secrets.nix — NOT symlinked here.
{ config, lib, caps, identity, ... }:

let
  dotfiles = "${config.home.homeDirectory}/.dotfiles";

  # Repo path == home-relative target path (the home/ tree mirrors ~), so a
  # single relative path names both the link source and its home.file key.
  link = path: config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/${path}";
  repoLink = path: config.lib.file.mkOutOfStoreSymlink "${dotfiles}/${path}";
  forcedRepoLink = path: {
    source = repoLink path;
    force = true;
  };

  # Turn a list of relative paths into { "<path>".source = link "<path>"; ... }.
  mkLinks = paths: lib.genAttrs paths (p: { source = link p; });

  # Machine-type overlay filename shared by mcp + skills (files are named
  # personal.json / work.json; identity is personal / work).
  overlay = "${identity}.json";
in
{
  home.file = lib.mkMerge [
    # ---- all machines -----------------------------------------------------
    (mkLinks [
      # z4h shell stack (z4h owns lifecycle; keep every file raw — see shell.nix).
      ".zshenv"
      ".config/zsh/.zshenv"
      ".config/zsh/.zshrc"
      ".config/zsh/.zprofile"
      ".config/zsh/.p10k.zsh"
      ".config/zsh/lib" # rebuild.zsh (replaces the retired chezmoi-apply lib)
      ".config/zsh/profile.d/worktrunk-aliases.zsh"
      ".config/zsh/profile.d/common-env.zsh" # non-secret flags (was the agenix zsh-env secret; WS1)

      # Editor / TUI / terminal configs.
      ".config/nvim" # stock LazyVim tree; LazyVim rewrites lazy-lock.json in place
      ".config/yazi"
      ".config/tmux"
      ".config/ghostty" # harmless everywhere; link always regardless of gui cap
      ".ideavimrc"

      # Dev tooling configs (mise config itself is generated in dev-tools.nix).
      ".config/git" # config (renamed from config.tmpl by dev-tools) + .gitignore_global
      # Link only the config: jj writes mutable repository metadata beneath
      # ~/.config/jj/repos, which must not land in the dotfiles checkout.
      ".config/jj/config.toml"
      ".config/worktrunk"
      ".config/dev-container"
      ".config/nushell/config.nu" # link the file, not the dir (nushell writes history/env.nu there)

      # Copilot IntelliJ instructions (single file; copilot writes runtime state in the dir).
      ".config/github-copilot/intellij/global-copilot-instructions.md"

      # Claude Code statusline + hooks. NOTE: settings.json is NOT linked here —
      # it is jq-merged by an activation script in ai-stack.nix so Claude's own
      # in-tool edits survive. CLAUDE.md is deployed per the locked gating map
      # (see report note: phase1 flagged the old chezmoi setup ignored it).
      ".claude/statusline-command.sh"
      ".claude/CLAUDE.md"
      ".claude/hooks/agent-journal-stop.sh"
      ".claude/hooks/emit-routing-context.sh"
      ".claude/hooks/wt-create.sh"
      ".claude/hooks/wt-remove.sh"

      # Codex CLI: shared agent instructions + worktree hooks. AGENTS.md is
      # machine-invariant (it renders the shared global-agent-instructions body
      # with no per-host conditionals). The two hook scripts are byte-identical
      # to the Claude ones above. hooks.json is NOT linked here — it is generated
      # personal-only below (its only live hook is the personal hippo session
      # hook; the old chezmoi PreToolUse/PostToolUse template guards are dead).
      ".codex/AGENTS.md"
      ".codex/hooks/wt-create.sh"
      ".codex/hooks/wt-remove.sh"
    ])

    # ---- identity: personal ----------------------------------------------
    (lib.optionalAttrs (identity == "personal") (mkLinks [
      ".config/zsh/profile.d/personal-shell-functions.zsh"
      ".config/zsh/profile.d/personal-secrets.zsh" # sources ~/.config/zsh/.personal.env (op-rendered)
      ".config/op/render-manifest" # op-render reads this at its default path (WS1)
      ".config/hippo" # local LM brain client config (config.toml + redact.toml)
    ]))

    # Codex hooks.json (personal only). The chezmoi source deployed this on every
    # machine, but its PreToolUse/PostToolUse hooks were chezmoi-template guards
    # (encrypted_* block + execute-template validation) that are inert under nix,
    # leaving only the personal hippo SessionStart hook as live content. Generated
    # rather than symlinked so the hippo path binds to this machine's homeDir.
    (lib.optionalAttrs (identity == "personal") {
      ".codex/hooks.json".text = builtins.toJSON {
        hooks.SessionStart = [
          {
            hooks = [
              {
                type = "command";
                command = "${config.home.homeDirectory}/.local/share/hippo-brain/shell/claude-session-hook.sh";
              }
            ];
          }
        ];
      };
    })

    # ---- identity: work ---------------------------------------------------
    (lib.optionalAttrs (identity == "work") (mkLinks [
      ".config/zsh/profile.d/work-shell-functions.zsh"
      ".config/zsh/profile.d/work-aws-shell-functions.zsh"
      ".config/zsh/profile.d/work-secrets.zsh"
    ]))

    # ---- NOT work (homelab access over Tailscale: personal only) ---------
    (lib.optionalAttrs (identity != "work") (mkLinks [
      ".config/zsh/profile.d/tailscale.zsh"
    ]))

    # ---- caps.atuin -------------------------------------------------------
    # Link only the config file; atuin writes history.db into the same dir.
    (lib.optionalAttrs caps.atuin (mkLinks [
      ".config/atuin/config.toml"
    ]))

    # ---- caps.mcp ---------------------------------------------------------
    # Master config + this machine's overlay. sync-mcp-configs (sync-hooks.nix)
    # reads these at activation time and also consults ~/.config/mcp/overrides/
    # if present — so guarantee that dir exists via a store-linked .keep marker
    # (sync globs overrides/*.json, so .keep is ignored).
    (lib.optionalAttrs caps.mcp (mkLinks [
      ".config/mcp/mcp-master.json"

      # AI CLI tool configs gated with the MCP fan-out (matches .chezmoiignore:
      # these are dropped on machines without the mcp cap). Each tool writes its
      # own runtime state into the surrounding dir but not into these managed
      # files, so a single-file out-of-store symlink is safe (copilot -> other
      # files in ~/.copilot; cursor -> other files in ~/.cursor). OpenCode's
      # live config is generated by mcp_sync; the old rules.toml is ignored by
      # current OpenCode and is intentionally not carried into the Nix layout.
      ".copilot/settings.json"
      ".cursor/cli-config.json"
    ]))
    (lib.optionalAttrs caps.mcp {
      ".config/mcp/overrides/.keep".text = "";
      # mkDefault: an external overlay repo may take ownership of this
      # machine's overlay (LOCKED contract — declared seam).
      ".config/mcp/machine/${overlay}".source = lib.mkDefault (link ".config/mcp/machine/${overlay}");
    })

    # ---- caps.skills ------------------------------------------------------
    # Manifest + this machine's overlay; sync-skills (sync-hooks.nix) reads them.
    (lib.optionalAttrs caps.skills (mkLinks [
      ".config/skills/skills-master.json"
    ]))
    (lib.optionalAttrs caps.skills {
      ".config/skills/machine/${overlay}".source = lib.mkDefault (link ".config/skills/machine/${overlay}");
    })
    # Personal skill links previously pointed into the retired chezmoi source
    # tree. Own each tool-native link explicitly so deleting that checkout does
    # not strand Codex, Cursor, Copilot, OpenCode, or Junie.
    (lib.optionalAttrs (caps.skills && identity == "personal") {
      ".config/opencode/skills/use-railway" = forcedRepoLink "skills/personal/use-railway";
      ".codex/skills/playwright" = forcedRepoLink "skills/personal/playwright";
      ".codex/skills/use-railway" = forcedRepoLink "skills/personal/use-railway";
      ".cursor/skills/use-railway" = forcedRepoLink "skills/personal/use-railway";
      ".copilot/skills/use-railway" = forcedRepoLink "skills/personal/use-railway";
      ".junie/skills/clerk" = forcedRepoLink "skills/personal/clerk";
      ".junie/skills/clerk-testing" = forcedRepoLink "skills/personal/clerk-testing";
      ".junie/skills/clerk-webhooks" = forcedRepoLink "skills/personal/clerk-webhooks";
      ".junie/skills/design-an-interface" = forcedRepoLink "skills/personal/design-an-interface";
      ".junie/skills/domain-model" = forcedRepoLink "skills/personal/domain-model";
      ".junie/skills/find-skills" = forcedRepoLink "skills/personal/find-skills";
      ".junie/skills/gh-axi" = forcedRepoLink "skills/personal/gh-axi";
      ".junie/skills/github-triage" = forcedRepoLink "skills/personal/github-triage";
      ".junie/skills/qa" = forcedRepoLink "skills/personal/qa";
      ".junie/skills/request-refactor-plan" = forcedRepoLink "skills/personal/request-refactor-plan";
      ".junie/skills/triage-issue" = forcedRepoLink "skills/personal/triage-issue";
      ".junie/skills/ubiquitous-language" = forcedRepoLink "skills/personal/ubiquitous-language";
    })

    # ---- caps.agent_journal ----------------------------------------------
    (lib.optionalAttrs caps.agent_journal (mkLinks [
      ".config/agent-journal" # config.toml + workstreams.toml (plain out-of-store symlinks)
      ".local/bin/agent-journal"
      ".local/bin/agent-note"
    ]))

    # ---- extension seam dirs (all machines) --------------------------------
    {
      # ~/.ssh is not dir-linked (only ~/.ssh/config is materialized, by
      # secrets.nix), so its config.d seam dir must exist via a real home.file
      # entry. The git and tmux conf.d seam dirs, by contrast, live *inside*
      # ".config/git" / ".config/tmux" whole-directory symlinks above — a
      # home.file entry for a path under an already-symlinked directory
      # collides with home-manager ("outside $HOME"). Those two ride their
      # parents' symlink for free and exist as real .keep files in the repo
      # tree instead (home/.config/git/conf.d/.keep, home/.config/tmux/conf.d/.keep).
      ".ssh/config.d/.keep".text = "";
    }
  ];

  # One link deliberately routed through the public rawDotfiles API so the
  # in-repo build exercises the same code path external wrappers use.
  rawDotfiles.trees = [
    {
      root = "${dotfiles}/home";
      paths = [ ".duckdbrc" ];
    }
  ];
}
