# Owns AeroSpace, SketchyBar, and JankyBorders symlinks and restart activation.
# Gate here with caps.tiling; do not duplicate these home.file keys in dotfiles.nix.
{
  config,
  lib,
  caps,
  identity,
  ...
}:

let
  dotfiles = "${config.home.homeDirectory}/.dotfiles";
  mkLink = path: config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/${path}";
in
{
  home.file = lib.mkMerge [
    (lib.mkIf caps.tiling {
      # Personal and work identities use separate static AeroSpace configs.
      ".config/aerospace/aerospace.toml".source = lib.mkDefault (
        mkLink ".config/aerospace/aerospace.${identity}.toml"
      );

      ".config/sketchybar/sketchybarrc".source = mkLink ".config/sketchybar/sketchybarrc";
      ".config/sketchybar/items".source = mkLink ".config/sketchybar/items";
      ".config/sketchybar/plugins".source = mkLink ".config/sketchybar/plugins";

      ".config/borders".source = mkLink ".config/borders";

      # plugins/aerospace.sh reads this capability from ../machine.env.
      ".config/sketchybar/machine.env".text = ''
        # Generated by nix-darwin from lib/machines.nix (caps.sketchybar_workspace_badges).
        SKETCHYBAR_WORKSPACE_BADGES=${if caps.sketchybar_workspace_badges then "1" else "0"}
      '';
    })
    (lib.mkIf (caps.tiling && identity == "personal") {
      # workspace-8-comms.sh service-mode layout script: only referenced
      # from aerospace.personal.toml's service-mode binding (`8 = [...]`).
      ".config/aerospace/layouts".source = mkLink ".config/aerospace/layouts";
    })
  ];

  # Restart after symlinks exist; missing packages and errors must not block a switch.
  home.activation.startTilingStack = lib.mkIf caps.tiling (
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      ( set -uo pipefail
        brew="/opt/homebrew/bin/brew"
        sketchybar="/opt/homebrew/bin/sketchybar"
        aerospace="/Applications/AeroSpace.app/Contents/MacOS/AeroSpace"
        aerospace_cli="/opt/homebrew/bin/aerospace"

        # Strip SUDO_* so brew services uses gui/<uid>, not the background
        # user/<uid> domain. Activation runs as the user in the Aqua session.
        brew_services() {
          /usr/bin/env -u SUDO_USER -u SUDO_UID -u SUDO_GID -u SUDO_COMMAND \
            "$brew" services "$@"
        }


        # ── sketchybar ──────────────────────────────────────────────────
        # Restart the Homebrew LaunchAgent to load config changes.
        if [ -x "$sketchybar" ] && [ -x "$brew" ]; then
          # Restart also handles loaded-but-errored jobs and services not yet loaded.
          brew_services restart sketchybar
        else
          echo "tiling-stack: sketchybar not installed yet: skipping" >&2
        fi

        # ── borders ─────────────────────────────────────────────────────
        # AeroSpace starts the single-instance borders process. A second
        # launchd-managed instance exits with "instance already running".

        # ── aerospace ────────────────────────────────────────────────────
        # AeroSpace must run once to register its start-at-login item.
        if [ -x "$aerospace" ]; then
          if /usr/bin/pgrep -x "AeroSpace" > /dev/null 2>&1; then
            "$aerospace_cli" reload-config
          else
            /usr/bin/open -a AeroSpace
          fi
        else
          echo "tiling-stack: aerospace not installed yet: skipping" >&2
        fi
      ) || echo "tiling-stack: restart failed: continuing (run 'brew services restart sketchybar' / 'open -a AeroSpace' manually)" >&2
    ''
  );
}
