# Tiling window-manager stack (AeroSpace + SketchyBar + JankyBorders).
#
# OWNERSHIP: this module owns ALL tiling-stack symlinks and the restart
# activation hook. modules/home/dotfiles.nix (T3) must NOT also define
# home.file entries for ".config/aerospace", ".config/sketchybar", or
# ".config/borders" — caps.tiling gating for the tiling stack lives here
# only, so the two modules never fight over the same home.file key.
{ config, lib, pkgs, caps, identity, ... }:

let
  dotfiles = "${config.home.homeDirectory}/.dotfiles";
  mkLink = path: config.lib.file.mkOutOfStoreSymlink "${dotfiles}/home/${path}";
in
{
  home.file = lib.mkMerge [
    (lib.mkIf caps.tiling {
      # aerospace.toml.tmpl had 3 identity-gated blocks (structural diff, not
      # scalar) — materialized as two full static files at port time; select
      # by identity here instead of templating. Lab never reaches this
      # (caps.tiling = false on lab-mac), so identity is always "personal"
      # or "work" whenever this branch evaluates.
      ".config/aerospace/aerospace.toml".source =
        mkLink ".config/aerospace/aerospace.${identity}.toml";

      ".config/sketchybar/sketchybarrc".source = mkLink ".config/sketchybar/sketchybarrc";
      ".config/sketchybar/items".source = mkLink ".config/sketchybar/items";
      ".config/sketchybar/plugins".source = mkLink ".config/sketchybar/plugins";

      ".config/borders".source = mkLink ".config/borders";

      # The one nix-generated scalar in the sketchybar tree — everything
      # else above is a raw out-of-store symlink. Ported from
      # dot_config/sketchybar/machine.env.tmpl (rm'd after this port).
      # plugins/aerospace.sh sources ../machine.env, defaults to enabled if
      # unset, and accepts 0/false/off/no as disabled.
      ".config/sketchybar/machine.env".text = ''
        # Generated by nix-darwin from lib/machines.nix (caps.sketchybar_workspace_badges).
        SKETCHYBAR_WORKSPACE_BADGES=${if caps.sketchybar_workspace_badges then "1" else "0"}
      '';
    })
    (lib.mkIf (caps.tiling && identity == "personal") {
      # workspace-8-comms.sh service-mode layout script — only referenced
      # from aerospace.personal.toml's service-mode binding (`8 = [...]`).
      ".config/aerospace/layouts".source = mkLink ".config/aerospace/layouts";
    })
  ];

  # Ported nearly verbatim from
  # .chezmoiscripts/darwin/run_onchange_after_start-tiling-stack.sh.tmpl.
  # The script's Go-template tiling gate becomes the outer lib.mkIf caps.tiling
  # here; body logic is unchanged. Bucket per contract: offline + fast +
  # idempotent -> home.activation, not `just sync`. Never fails the switch —
  # any error is caught and reported as a warning so a half-installed brew
  # stack can't block the rest of the activation.
  home.activation.startTilingStack = lib.mkIf caps.tiling (
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      ( set -uo pipefail
        # Fresh machines may not have run `brew bundle` yet — skip quietly
        # instead of failing the whole activation; the next switch after
        # `brew bundle` starts the stack.

        # ── sketchybar ──────────────────────────────────────────────────
        # Managed via Homebrew services; the LaunchAgent is created by brew
        # services. If already running, restart to pick up config changes
        # this switch just wrote.
        if command -v sketchybar > /dev/null 2>&1; then
          if brew services list | ${pkgs.ripgrep}/bin/rg -q '^sketchybar.*started'; then
            brew services restart sketchybar
          else
            brew services start sketchybar
          fi
        else
          echo "tiling-stack: sketchybar not installed yet — skipping" >&2
        fi

        # ── aerospace ────────────────────────────────────────────────────
        # Installed as a cask (not a brew formula), so Homebrew services
        # don't manage it. start-at-login = true in aerospace.toml registers
        # the macOS login item, but only after the app has run at least
        # once. Open it here if not running.
        if command -v aerospace > /dev/null 2>&1; then
          if pgrep -x "AeroSpace" > /dev/null 2>&1; then
            aerospace reload-config
          else
            open -a AeroSpace
          fi
        else
          echo "tiling-stack: aerospace not installed yet — skipping" >&2
        fi
      ) || echo "tiling-stack: restart failed — continuing (run 'brew services restart sketchybar' / 'open -a AeroSpace' manually)" >&2
    ''
  );
}
