#!/usr/bin/env bash
# Prove Worktrunk cannot pass malformed generated messages through to Git.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
generator="${repo_root}/home/.local/bin/worktrunk-commit-generator"
config="${repo_root}/home/.config/worktrunk/config.toml"
[ -x "${generator}" ] || { echo "FAIL: ${generator} is not executable" >&2; exit 1; }
[ -f "${config}" ] || { echo "FAIL: ${config} is not a regular file" >&2; exit 1; }
[ ! -L "${config}" ] || { echo "FAIL: ${config} must not be a symlink" >&2; exit 1; }

# Parse the checked-in config independently of the installed Worktrunk version.
# These assertions catch a store path accidentally committed as file contents
# and preserve the settings whose absence changes worktree and merge behavior.
"${repo_root}/scripts/assert-worktrunk-config.py" "${config}"

fixture="$(mktemp -d)"
trap 'rm -rf "${fixture}"' EXIT

assert_invalid() {
  local message="$1" expected="$2"
  if printf '%s' "${message}" | "${generator}" --validate \
    >"${fixture}/validate.out" 2>"${fixture}/validate.err"; then
    echo "FAIL: invalid message passed: ${message}" >&2
    exit 1
  fi
  if ! rg -Fq "${expected}" "${fixture}/validate.err"; then
    echo "FAIL: expected validation error '${expected}'" >&2
    cat "${fixture}/validate.err" >&2
    exit 1
  fi
}

printf '%s\n' "fix(parser)!: reject malformed output" "" "Keep the previous candidate out of Git." \
  | "${generator}" --validate >"${fixture}/valid.out"
rg -Fxq "fix(parser)!: reject malformed output" "${fixture}/valid.out"
printf "%s\n" "fix: don't drop user's note" | "${generator}" --validate >/dev/null
printf "%s\n" "docs: preserve users' files" | "${generator}" --validate >/dev/null
printf "%s\n" "fix: route model and assistant harness settings" \
  | "${generator}" --validate >/dev/null
printf "%s\n" "ci: validate generated commits" | "${generator}" --validate >/dev/null

assert_invalid $'This changes parsing\n\nfix: parse output' "Conventional Commit subject"
assert_invalid "fix: reject a stray delimiter)" "unmatched delimiter"
assert_invalid "fix: stop the retry." "must not end with a period"
assert_invalid "fix: generated by Claude" "must not reference AI"
assert_invalid "fix: tune Claude hook timeout" "must not reference AI"
assert_invalid "chore: generated by GPT-4o" "must not reference AI"
assert_invalid $'fix: describe the change\nExplanation without a separator' "must follow a blank line"

# --- commit-msg gate (--validate-commit-file) ------------------------------
# The lefthook commit-msg job runs this mode on every commit in this repo. It
# deliberately diverges from --validate: no AI-attribution rule, git's own
# message semantics, and an exemption for the subjects git writes itself.
commit_file="${fixture}/COMMIT_EDITMSG"

assert_commit_file() {
  local expected_status="$1" message="$2" label="$3"
  printf '%s\n' "${message}" >"${commit_file}"
  set +e
  "${generator}" --validate-commit-file "${commit_file}" \
    >"${fixture}/gate.out" 2>"${fixture}/gate.err"
  local status=$?
  set -e
  if [ "${status}" != "${expected_status}" ]; then
    echo "FAIL: ${label}: expected exit ${expected_status}, got ${status}" >&2
    cat "${fixture}/gate.err" >&2
    exit 1
  fi
}

# The defect this gate exists for: a `(#NN)` placeholder filled in without an
# issue number, leaving the closing paren behind.
assert_commit_file 1 "chore: add root ruff.toml, drop dashboard-tabs)" "stray trailing paren"
assert_commit_file 1 "This looks like the update flow" "agent narration as subject"
assert_commit_file 1 "fix: stop the retry." "trailing period"

# Naming an AI tool in a subject is legitimate here; --validate still rejects
# it for generated candidates, this mode must not.
assert_commit_file 0 "fix: tune Claude hook timeout" "Claude named in subject"
assert_commit_file 0 "feat: script pin-bump flow (#42)" "whole issue reference"

# Subjects git generates are not the author's to reword.
assert_commit_file 0 'Revert "chore: drop dashboard-tabs"' "git revert"
assert_commit_file 0 "Merge branch main into topic" "git merge"
assert_commit_file 0 "fixup! chore: add ruff.toml" "git commit --fixup"

# git's own message file semantics.
printf 'feat: real subject\n\nBody.\n\n# Please enter the commit message\n' >"${commit_file}"
"${generator}" --validate-commit-file "${commit_file}" >/dev/null 2>&1 ||
  { echo "FAIL: comment lines must be stripped before validation" >&2; exit 1; }
printf 'feat: real subject\n\n%s\ndiff --git a/x b/x\n+stray)\n' \
  "# ------------------------ >8 ------------------------" >"${commit_file}"
"${generator}" --validate-commit-file "${commit_file}" >/dev/null 2>&1 ||
  { echo "FAIL: --verbose diff below the scissors line must be ignored" >&2; exit 1; }

# lefthook must actually run the gate; a job that exists but is not wired to
# the commit-msg hook is the same silent no-op as a glob that matches nothing.
if ! rg -Fq -- "--validate-commit-file" "${repo_root}/lefthook.yml"; then
  echo "FAIL: lefthook.yml commit-msg does not run the commit-message gate" >&2
  exit 1
fi

cat >"${fixture}/claude" <<'MOCK'
#!/usr/bin/env bash
set -euo pipefail
count_file="${MOCK_DIR}/count"
count=0
[ ! -f "${count_file}" ] || count="$(<"${count_file}")"
count=$((count + 1))
printf '%s' "${count}" >"${count_file}"
printf '%s\n' "$*" >>"${MOCK_DIR}/args"
printf 'CLAUDECODE=<%s> MAX_THINKING_TOKENS=<%s>\n' \
  "${CLAUDECODE-unset}" "${MAX_THINKING_TOKENS-unset}" >>"${MOCK_DIR}/env"
cat >"${MOCK_DIR}/prompt-${count}"
response="${MOCK_DIR}/response-${count}"
rc_file="${MOCK_DIR}/rc-${count}"
[ ! -f "${response}" ] || cat "${response}"
[ ! -f "${rc_file}" ] || exit "$(<"${rc_file}")"
MOCK
chmod +x "${fixture}/claude"

run_generator() {
  MOCK_DIR="${fixture}" CLAUDE_BIN="${fixture}/claude" WORKTRUNK_COMMIT_ATTEMPTS=2 \
    "${generator}"
}

printf '%s\n' "fix: unbalanced output)" >"${fixture}/response-1"
printf '%s\n' "fix: validate generated output" >"${fixture}/response-2"
printf '%s' "Generate from this diff" | run_generator >"${fixture}/generated.out"
if [ "$(<"${fixture}/count")" -ne 2 ]; then
  echo "FAIL: invalid first result did not trigger exactly one retry" >&2
  exit 1
fi
rg -Fxq "fix: validate generated output" "${fixture}/generated.out"
rg -Fq "previous candidate failed local validation" "${fixture}/prompt-2"

expected_flags="-p --no-session-persistence --model=haiku --tools= --safe-mode --disable-slash-commands --setting-sources=user --system-prompt="
if [ "$(sed -n '1p' "${fixture}/args")" != "${expected_flags}" ]; then
  echo "FAIL: Claude safety flags drifted" >&2
  cat "${fixture}/args" >&2
  exit 1
fi
if ! rg -Fxq "CLAUDECODE=<> MAX_THINKING_TOKENS=<0>" "${fixture}/env"; then
  echo "FAIL: Claude environment controls drifted" >&2
  cat "${fixture}/env" >&2
  exit 1
fi

rm -f "${fixture}/count"
printf '%s\n' "docs: bad." >"${fixture}/response-1"
printf '%s\n' "docs: still bad." >"${fixture}/response-2"
if printf '%s' "Generate" | run_generator >"${fixture}/failure.out" 2>"${fixture}/failure.err"; then
  echo "FAIL: exhausted invalid generation unexpectedly succeeded" >&2
  exit 1
fi
if [ -s "${fixture}/failure.out" ]; then
  echo "FAIL: rejected model output leaked to stdout" >&2
  cat "${fixture}/failure.out" >&2
  exit 1
fi
rg -Fq "rejected generated commit message after 2 attempts" "${fixture}/failure.err"

echo "all Worktrunk commit-generator checks passed"
