#!/usr/bin/env bash
# Prove Worktrunk cannot pass malformed generated messages through to Git.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
generator="${repo_root}/home/.local/bin/worktrunk-commit-generator"
config="${repo_root}/home/.config/worktrunk/config.toml"
[ -x "${generator}" ] || { echo "FAIL: ${generator} is not executable" >&2; exit 1; }
[ -f "${config}" ] || { echo "FAIL: ${config} is not a regular file" >&2; exit 1; }
[ ! -L "${config}" ] || { echo "FAIL: ${config} must not be a symlink" >&2; exit 1; }

# Parse the checked-in config independently of the installed Worktrunk version.
# These assertions catch a store path accidentally committed as file contents
# and preserve the settings whose absence changes worktree and merge behavior.
WORKTRUNK_CONFIG="${config}" python3 <<'PY'
import os
import pathlib
import tomllib

config = tomllib.loads(pathlib.Path(os.environ["WORKTRUNK_CONFIG"]).read_text())
assert config["worktree-path"] == "{{ repo_path }}/../{{ repo }}-{{ branch | sanitize }}"
assert config["pre-start"] == [{"copy": "wt step copy-ignored"}]
assert config["list"]["json-schema"] == 2
assert config["commit"]["stage"] == "all"
assert config["commit"]["generation"]["command"]
assert config["merge"] == {"squash": True, "commit": True}
PY

fixture="$(mktemp -d)"
trap 'rm -rf "${fixture}"' EXIT

assert_invalid() {
  local message="$1" expected="$2"
  if printf '%s' "${message}" | "${generator}" --validate \
    >"${fixture}/validate.out" 2>"${fixture}/validate.err"; then
    echo "FAIL: invalid message passed: ${message}" >&2
    exit 1
  fi
  if ! rg -Fq "${expected}" "${fixture}/validate.err"; then
    echo "FAIL: expected validation error '${expected}'" >&2
    cat "${fixture}/validate.err" >&2
    exit 1
  fi
}

printf '%s\n' "fix(parser)!: reject malformed output" "" "Keep the previous candidate out of Git." \
  | "${generator}" --validate >"${fixture}/valid.out"
rg -Fxq "fix(parser)!: reject malformed output" "${fixture}/valid.out"
printf "%s\n" "fix: don't drop user's note" | "${generator}" --validate >/dev/null
printf "%s\n" "docs: preserve users' files" | "${generator}" --validate >/dev/null
printf "%s\n" "fix: route model and assistant harness settings" \
  | "${generator}" --validate >/dev/null
printf "%s\n" "ci: validate generated commits" | "${generator}" --validate >/dev/null

assert_invalid $'This changes parsing\n\nfix: parse output' "Conventional Commit subject"
assert_invalid "fix: reject a stray delimiter)" "unmatched delimiter"
assert_invalid "fix: stop the retry." "must not end with a period"
assert_invalid "fix: generated by Claude" "must not reference AI"
assert_invalid "fix: tune Claude hook timeout" "must not reference AI"
assert_invalid "chore: generated by GPT-4o" "must not reference AI"
assert_invalid $'fix: describe the change\nExplanation without a separator' "must follow a blank line"

cat >"${fixture}/claude" <<'MOCK'
#!/usr/bin/env bash
set -euo pipefail
count_file="${MOCK_DIR}/count"
count=0
[ ! -f "${count_file}" ] || count="$(<"${count_file}")"
count=$((count + 1))
printf '%s' "${count}" >"${count_file}"
printf '%s\n' "$*" >>"${MOCK_DIR}/args"
printf 'CLAUDECODE=<%s> MAX_THINKING_TOKENS=<%s>\n' \
  "${CLAUDECODE-unset}" "${MAX_THINKING_TOKENS-unset}" >>"${MOCK_DIR}/env"
cat >"${MOCK_DIR}/prompt-${count}"
response="${MOCK_DIR}/response-${count}"
rc_file="${MOCK_DIR}/rc-${count}"
[ ! -f "${response}" ] || cat "${response}"
[ ! -f "${rc_file}" ] || exit "$(<"${rc_file}")"
MOCK
chmod +x "${fixture}/claude"

run_generator() {
  MOCK_DIR="${fixture}" CLAUDE_BIN="${fixture}/claude" WORKTRUNK_COMMIT_ATTEMPTS=2 \
    "${generator}"
}

printf '%s\n' "fix: unbalanced output)" >"${fixture}/response-1"
printf '%s\n' "fix: validate generated output" >"${fixture}/response-2"
printf '%s' "Generate from this diff" | run_generator >"${fixture}/generated.out"
if [ "$(<"${fixture}/count")" -ne 2 ]; then
  echo "FAIL: invalid first result did not trigger exactly one retry" >&2
  exit 1
fi
rg -Fxq "fix: validate generated output" "${fixture}/generated.out"
rg -Fq "previous candidate failed local validation" "${fixture}/prompt-2"

expected_flags="-p --no-session-persistence --model=haiku --tools= --safe-mode --disable-slash-commands --setting-sources=user --system-prompt="
if [ "$(sed -n '1p' "${fixture}/args")" != "${expected_flags}" ]; then
  echo "FAIL: Claude safety flags drifted" >&2
  cat "${fixture}/args" >&2
  exit 1
fi
if ! rg -Fxq "CLAUDECODE=<> MAX_THINKING_TOKENS=<0>" "${fixture}/env"; then
  echo "FAIL: Claude environment controls drifted" >&2
  cat "${fixture}/env" >&2
  exit 1
fi

rm -f "${fixture}/count"
printf '%s\n' "docs: bad." >"${fixture}/response-1"
printf '%s\n' "docs: still bad." >"${fixture}/response-2"
if printf '%s' "Generate" | run_generator >"${fixture}/failure.out" 2>"${fixture}/failure.err"; then
  echo "FAIL: exhausted invalid generation unexpectedly succeeded" >&2
  exit 1
fi
if [ -s "${fixture}/failure.out" ]; then
  echo "FAIL: rejected model output leaked to stdout" >&2
  cat "${fixture}/failure.out" >&2
  exit 1
fi
rg -Fq "rejected generated commit message after 2 attempts" "${fixture}/failure.err"

echo "all Worktrunk commit-generator checks passed"
